{
 "title": "Monitoramento",
 "description": "Monitoramento Servidor e Containers",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "SERVIDOR ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU - SERVIDOR",
   "type": "gauge",
   "description": "CPU DO MEU NOTEBOOK, ONDE ESTÁ SENDO UM SERVIDOR PARA RODAR OS CONTAINERS",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(windows_cpu_time_total{job=\"windows\",mode=\"idle\"}[30s])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MEMORIA RAM",
   "type": "gauge",
   "description": "MOSTRA USO DE MEMORIA RAM DO MEU NOTEBOOK",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (windows_memory_available_bytes{job=\"windows\"} / windows_memory_physical_total_bytes{job=\"windows\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disco C:  - ESPAÇO UTILIZADO",
   "type": "gauge",
   "description": "Mostra a quantidade de espaço no Disco C: que está sendo utilizada.",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (windows_logical_disk_free_bytes{volume=\"C:\"} \r\n/ windows_logical_disk_size_bytes{volume=\"C:\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "REDE -  SERVIDOR",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(windows_net_bytes_received_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CONTAINERS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "DISPONIBILIDADE - CONTAINERS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_last_seen{container_label_com_docker_compose_service!=\"\"}",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "MEMORIA RAM - CONTAINERS",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name) (container_memory_usage_bytes{image!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "REDE - CONTAINERS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (name) (\r\n  rate(container_network_receive_bytes_total{interface=\"eth0\", name!=\"\"}[1m])\r\n)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU - CONTAINERS",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{image!=\"\"}[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}